export const SERVICE_TYPES_INIT_LOADING = 'SERVICE_TYPES_INIT_LOADING'
export const SERVICE_TYPES_INIT_DONE = 'SERVICE_TYPES_INIT_DONE'
export const SERVICE_TYPES_INIT_ERROR = 'SERVICE_TYPES_INIT_ERROR'