export const SERVICE_TYPES_INIT_LOADING = 'SERVICE_TYPES_INIT_LOADING'
export const SERVICE_TYPES_INIT_DONE = 'SERVICE_TYPES_INIT_DONE'
export const SERVICE_TYPES_INIT_ERROR = 'SERVICE_TYPES_INIT_ERROR'

export const SEARCH_DATA_UPDATE = 'SEARCH_DATA_UPDATE'

export const SEARCH_RESULTS_UPDATE_LOADING = 'SEARCH_RESULTS_UPDATE_LOADING'
export const SEARCH_RESULTS_UPDATE_DONE = 'SEARCH_RESULTS_UPDATE_DONE'
export const SEARCH_RESULTS_UPDATE_ERROR = 'SEARCH_RESULTS_UPDATE_ERROR'

export const CHAT_CURRENT_CHAT_UPDATE = 'CHAT_CURRENT_CHAT_UPDATE'
export const CHAT_SEND_MSG = 'CHAT_SEND_MSG'
export const CHAT_RECV_MSG = 'CHAT_RECV_MSG'
export const CHAT_INIT_LOADING = 'CHAT_INIT_LOADING'
export const CHAT_INIT_DONE = 'CHAT_INIT_DONE'
export const CHAT_INIT_ERROR = 'CHAT_INIT_ERROR'