export const API_STATUS_NONE = 'API_STATUS_NONE'
export const API_STATUS_LOADING = 'API_STATUS_LOADING'
export const API_STATUS_DONE = 'API_STATUS_DONE'
export const API_STATUS_ERROR = 'API_STATUS_ERROR'

export const API_STATUS_ERROR_404 = 'API_STATUS_ERROR_404'